pub const PES = @import("PackedEnumSet").PackedEnumSet;
pub const AccessFlagBits2 = enum(u64) {
    @"2_none" = 0,
    @"2_indirect_command_read_bit" = 1,
    @"2_index_read_bit" = 2,
    @"2_vertex_attribute_read_bit" = 4,
    @"2_uniform_read_bit" = 8,
    @"2_input_attachment_read_bit" = 16,
    @"2_shader_read_bit" = 32,
    @"2_shader_write_bit" = 64,
    @"2_color_attachment_read_bit" = 128,
    @"2_color_attachment_write_bit" = 256,
    @"2_depth_stencil_attachment_read_bit" = 512,
    @"2_depth_stencil_attachment_write_bit" = 1024,
    @"2_transfer_read_bit" = 2048,
    @"2_transfer_write_bit" = 4096,
    @"2_host_read_bit" = 8192,
    @"2_host_write_bit" = 16384,
    @"2_memory_read_bit" = 32768,
    @"2_memory_write_bit" = 65536,
    @"2_command_preprocess_read_bit_nv" = 131072,
    @"2_command_preprocess_write_bit_nv" = 262144,
    @"2_color_attachment_read_noncoherent_bit_ext" = 524288,
    @"2_conditional_rendering_read_bit_ext" = 1048576,
    @"2_acceleration_structure_read_bit_nv" = 2097152,
    @"2_acceleration_structure_write_bit_nv" = 4194304,
    @"2_shading_rate_image_read_bit_nv" = 8388608,
    @"2_fragment_density_map_read_bit_ext" = 16777216,
    @"2_transform_feedback_write_bit_ext" = 33554432,
    @"2_transform_feedback_counter_read_bit_ext" = 67108864,
    @"2_transform_feedback_counter_write_bit_ext" = 134217728,
    @"2_shader_sampled_read_bit" = 4294967296,
    @"2_shader_storage_read_bit" = 8589934592,
    @"2_shader_storage_write_bit" = 17179869184,
    @"2_video_decode_read_bit_khr" = 34359738368,
    @"2_video_decode_write_bit_khr" = 68719476736,
    @"2_video_encode_read_bit_khr" = 137438953472,
    @"2_video_encode_write_bit_khr" = 274877906944,
    @"2_invocation_mask_read_bit_huawei" = 549755813888,
    @"2_shader_binding_table_read_bit_khr" = 1099511627776,
    @"2_descriptor_buffer_read_bit_ext" = 2199023255552,
    @"2_optical_flow_read_bit_nv" = 4398046511104,
    @"2_optical_flow_write_bit_nv" = 8796093022208,
    @"2_micromap_read_bit_ext" = 17592186044416,
    @"2_micromap_write_bit_ext" = 35184372088832,
    const Self = @This();
    pub const @"2_none_khr" = Self.@"2_none";
    pub const @"2_indirect_command_read_bit_khr" = Self.@"2_indirect_command_read_bit";
    pub const @"2_index_read_bit_khr" = Self.@"2_index_read_bit";
    pub const @"2_vertex_attribute_read_bit_khr" = Self.@"2_vertex_attribute_read_bit";
    pub const @"2_uniform_read_bit_khr" = Self.@"2_uniform_read_bit";
    pub const @"2_input_attachment_read_bit_khr" = Self.@"2_input_attachment_read_bit";
    pub const @"2_shader_read_bit_khr" = Self.@"2_shader_read_bit";
    pub const @"2_shader_write_bit_khr" = Self.@"2_shader_write_bit";
    pub const @"2_color_attachment_read_bit_khr" = Self.@"2_color_attachment_read_bit";
    pub const @"2_color_attachment_write_bit_khr" = Self.@"2_color_attachment_write_bit";
    pub const @"2_depth_stencil_attachment_read_bit_khr" = Self.@"2_depth_stencil_attachment_read_bit";
    pub const @"2_depth_stencil_attachment_write_bit_khr" = Self.@"2_depth_stencil_attachment_write_bit";
    pub const @"2_transfer_read_bit_khr" = Self.@"2_transfer_read_bit";
    pub const @"2_transfer_write_bit_khr" = Self.@"2_transfer_write_bit";
    pub const @"2_host_read_bit_khr" = Self.@"2_host_read_bit";
    pub const @"2_host_write_bit_khr" = Self.@"2_host_write_bit";
    pub const @"2_memory_read_bit_khr" = Self.@"2_memory_read_bit";
    pub const @"2_memory_write_bit_khr" = Self.@"2_memory_write_bit";
    pub const @"2_shader_sampled_read_bit_khr" = Self.@"2_shader_sampled_read_bit";
    pub const @"2_shader_storage_read_bit_khr" = Self.@"2_shader_storage_read_bit";
    pub const @"2_shader_storage_write_bit_khr" = Self.@"2_shader_storage_write_bit";
    pub const @"2_command_preprocess_read_bit_ext" = Self.@"2_command_preprocess_read_bit_nv";
    pub const @"2_command_preprocess_write_bit_ext" = Self.@"2_command_preprocess_write_bit_nv";
    pub const @"2_fragment_shading_rate_attachment_read_bit_khr" = Self.@"2_shading_rate_image_read_bit_nv";
    pub const @"2_acceleration_structure_read_bit_khr" = Self.@"2_acceleration_structure_read_bit_nv";
    pub const @"2_acceleration_structure_write_bit_khr" = Self.@"2_acceleration_structure_write_bit_nv";
};
pub const AccessFlags2 = PES(AccessFlagBits2);
pub const Bool32 = enum(u32) {
    false = 0,
    true = 1,
};
