pub const PES = @import("PackedEnumSet");
pub const AccessFlags2 = enum(u64) {
    none = 0,
    indirect_command_read_bit = 1,
    index_read_bit = 2,
    vertex_attribute_read_bit = 4,
    uniform_read_bit = 8,
    input_attachment_read_bit = 16,
    shader_read_bit = 32,
    shader_write_bit = 64,
    color_attachment_read_bit = 128,
    color_attachment_write_bit = 256,
    depth_stencil_attachment_read_bit = 512,
    depth_stencil_attachment_write_bit = 1024,
    transfer_read_bit = 2048,
    transfer_write_bit = 4096,
    host_read_bit = 8192,
    host_write_bit = 16384,
    memory_read_bit = 32768,
    memory_write_bit = 65536,
    command_preprocess_read_bit_nv = 131072,
    command_preprocess_write_bit_nv = 262144,
    color_attachment_read_noncoherent_bit_ext = 524288,
    conditional_rendering_read_bit_ext = 1048576,
    acceleration_structure_read_bit_nv = 2097152,
    acceleration_structure_write_bit_nv = 4194304,
    shading_rate_image_read_bit_nv = 8388608,
    fragment_density_map_read_bit_ext = 16777216,
    transform_feedback_write_bit_ext = 33554432,
    transform_feedback_counter_read_bit_ext = 67108864,
    transform_feedback_counter_write_bit_ext = 134217728,
    shader_sampled_read_bit = 4294967296,
    shader_storage_read_bit = 8589934592,
    shader_storage_write_bit = 17179869184,
    video_decode_read_bit_khr = 34359738368,
    video_decode_write_bit_khr = 68719476736,
    video_encode_read_bit_khr = 137438953472,
    video_encode_write_bit_khr = 274877906944,
    invocation_mask_read_bit_huawei = 549755813888,
    shader_binding_table_read_bit_khr = 1099511627776,
    descriptor_buffer_read_bit_ext = 2199023255552,
    optical_flow_read_bit_nv = 4398046511104,
    optical_flow_write_bit_nv = 8796093022208,
    micromap_read_bit_ext = 17592186044416,
    micromap_write_bit_ext = 35184372088832,
    const Self = @This();
    pub const none_khr = Self.none;
    pub const indirect_command_read_bit_khr = Self.indirect_command_read_bit;
    pub const index_read_bit_khr = Self.index_read_bit;
    pub const vertex_attribute_read_bit_khr = Self.vertex_attribute_read_bit;
    pub const uniform_read_bit_khr = Self.uniform_read_bit;
    pub const input_attachment_read_bit_khr = Self.input_attachment_read_bit;
    pub const shader_read_bit_khr = Self.shader_read_bit;
    pub const shader_write_bit_khr = Self.shader_write_bit;
    pub const color_attachment_read_bit_khr = Self.color_attachment_read_bit;
    pub const color_attachment_write_bit_khr = Self.color_attachment_write_bit;
    pub const depth_stencil_attachment_read_bit_khr = Self.depth_stencil_attachment_read_bit;
    pub const depth_stencil_attachment_write_bit_khr = Self.depth_stencil_attachment_write_bit;
    pub const transfer_read_bit_khr = Self.transfer_read_bit;
    pub const transfer_write_bit_khr = Self.transfer_write_bit;
    pub const host_read_bit_khr = Self.host_read_bit;
    pub const host_write_bit_khr = Self.host_write_bit;
    pub const memory_read_bit_khr = Self.memory_read_bit;
    pub const memory_write_bit_khr = Self.memory_write_bit;
    pub const shader_sampled_read_bit_khr = Self.shader_sampled_read_bit;
    pub const shader_storage_read_bit_khr = Self.shader_storage_read_bit;
    pub const shader_storage_write_bit_khr = Self.shader_storage_write_bit;
    pub const command_preprocess_read_bit_ext = Self.command_preprocess_read_bit_nv;
    pub const command_preprocess_write_bit_ext = Self.command_preprocess_write_bit_nv;
    pub const fragment_shading_rate_attachment_read_bit_khr = Self.shading_rate_image_read_bit_nv;
    pub const acceleration_structure_read_bit_khr = Self.acceleration_structure_read_bit_nv;
    pub const acceleration_structure_write_bit_khr = Self.acceleration_structure_write_bit_nv;
};
