pub const PES = @import("PackedEnumSet").PackedEnumSet;
pub const AccessFlagBits = enum(u32) {
    none = 0,
    indirect_command_read_bit = 1,
    index_read_bit = 2,
    vertex_attribute_read_bit = 4,
    uniform_read_bit = 8,
    input_attachment_read_bit = 16,
    shader_read_bit = 32,
    shader_write_bit = 64,
    color_attachment_read_bit = 128,
    color_attachment_write_bit = 256,
    depth_stencil_attachment_read_bit = 512,
    depth_stencil_attachment_write_bit = 1024,
    transfer_read_bit = 2048,
    transfer_write_bit = 4096,
    host_read_bit = 8192,
    host_write_bit = 16384,
    memory_read_bit = 32768,
    memory_write_bit = 65536,
    command_preprocess_read_bit_nv = 131072,
    command_preprocess_write_bit_nv = 262144,
    color_attachment_read_noncoherent_bit_ext = 524288,
    conditional_rendering_read_bit_ext = 1048576,
    acceleration_structure_read_bit_nv = 2097152,
    acceleration_structure_write_bit_nv = 4194304,
    shading_rate_image_read_bit_nv = 8388608,
    fragment_density_map_read_bit_ext = 16777216,
    transform_feedback_write_bit_ext = 33554432,
    transform_feedback_counter_read_bit_ext = 67108864,
    transform_feedback_counter_write_bit_ext = 134217728,
    flag_bits_max_enum = 2147483647,
    const Self = @This();
    pub const command_preprocess_write_bit_ext = Self.command_preprocess_write_bit_nv;
    pub const command_preprocess_read_bit_ext = Self.command_preprocess_read_bit_nv;
    pub const fragment_shading_rate_attachment_read_bit_khr = Self.shading_rate_image_read_bit_nv;
    pub const acceleration_structure_write_bit_khr = Self.acceleration_structure_write_bit_nv;
    pub const acceleration_structure_read_bit_khr = Self.acceleration_structure_read_bit_nv;
    pub const none_khr = Self.none;
};
pub const AccessFlags = PES(AccessFlagBits);
